### PR TITLE
set Docker

### PR DESCRIPTION
**Pull request by kaumnen**

### CODE REVIEW

**Comment by kaumnen** [comment]
not closing #1 due to the fact that gh actions still need to be done

**Review by flppht — APPROVED** [review]
no new line in .dockerignore, will this make a problem? 

other seems great for rookie as myself (:

**Review by flppht — APPROVED** [review]
this is approval, sorry

**Review by flppht — APPROVED** [review]
both are, what is happening?

**Comment by kaumnen** [comment]
let me check. as for .dockerignore file, seems like that's supposed behaviour with prettier formatting

**Pull request merged**
